# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://kylexis.com
title: Kyle & Alexis are getting Married
email: kylermix@gmail.com
author: Kyle Mix & Alexis Beach
description: > # "Homepage for Chelsey Contillo and Michael Gully-Santiago
 wedding in Palm Springs on September 15, 2018.
copyright: 'Copyright &copy; 2018 Kyle & Alexis. All Rights Reserved.'
credits: 'Credits: forked from Shane Weng.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    text: WeDontHaveABlog
    url: https://kylexis.com
  - title: instagram
    text: dontClickMe
    url: https://kylexis.com
  - title: shower
    text: NotUs
    url: https://kylexis.com
  - title: spotify
    text: StillNotUs
    url: https://kylexis.com
  - title: envelope-open-o
    text: youGetIt
    url: https://kylexis.com
  - title: gift
    text: ReallyNotUs
    url: https://kylexis.com
