# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://chugly.github.io/wedding/
title: Kyle & Alexis are getting Married
email: kylermix@gmail.com
author: Kyle Mix & Alexis Beach
description: > # "Homepage for Chelsey Contillo and Michael Gully-Santiago
 wedding in Palm Springs on September 15, 2018.
copyright: 'Copyright &copy; 2018 Kyle & Alexis. All Rights Reserved.'
credits: 'Credits: forked from Shane Weng.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    text: WeDontHaveABlog
    url: http://chugly.github.io/
  - title: instagram
    text: dontClickMe
    url: https://www.instagram.com/explore/tags/chuglywed/
  - title: shower
    text: NotUs
    url: https://www.airbnb.com/wishlists/204150664/join?invite_code=QNCUYPRG&inviter_id=583562
  - title: spotify
    text: StillNotUs
    url: https://open.spotify.com/user/126045799/playlist/1KnnWPmEOm3PiQ93mpAQuF
  - title: envelope-open-o
    text: youGetIt
    url: https://goo.gl/forms/PDVQXXai2lVgKkqW2
  - title: gift
    text: ReallyNotUs
    url: https://www.zola.com/registry/chugly
