# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://kylexis.com
title: Kyle & Alexis are getting Married
email: kylermix@gmail.com
author: Kyle Mix & Alexis Beach
description: > # "Homepage for Chelsey Contillo and Michael Gully-Santiago
 Palm Springs + September 15, 2018.
copyright: 'Copyright &copy; 2018 Kyle & Alexis. All Rights Reserved.'
credits: 'Credits: forked from Shane Weng.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    text: His
    url: https://www.instagram.com/kylermix/
  - title: instagram
    text: Hers
    url: https://www.instagram.com/stitchmasterbeach/
  - title: hotel
    text: The Avalon
    url: https://www.avalon-hotel.com/palm-springs/
  - title: hotel
    text: The Rowan
    url: http://www.rowanpalmsprings.com/
  - title: at
    text: Contact us
    url: mailto:us@kylexis.com
  - title: gift
    text: Our registry
    url: https://www.zola.com/registry/beachmix/
